[theme]

# Primary accent for interactive elements
primaryColor = 'hsl(220, 60%, 30%)'

## Background color for the main content area
backgroundColor = 'hsl(220, 5%, 99%)'
#
## Background color for sidebar and most interactive widgets
#secondaryBackgroundColor = '#B9F1C0'

## Color used for almost all text
#textColor = 'hsl(0,0%,100%)'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"