name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
       branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and publish image to GCR
      uses: carbonchain/action-container-registry@v1.1
      with:
        project_id: solar-and-heat-pump
        dockerfile: ./Dockerfile
        image: gcr.io/solar-and-heat-pump/app
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

- name: Deploy service to Cloud Run
  uses: stefda/action-cloud-run@v1.6
  with:
    image: gcr.io/solar-and-heat-pump/app
    service: solar-and-heat-pump-app
    project: solar-and-heat-pump
    region: europe-north1
    service key: ${{ secrets.GCLOUD_AUTH }}

